#!/usr/bin/env python3
import sys
import pprint

from thrift import Thrift
from thrift.transport import TTransport, TSocket, TSSLSocket, THttpClient
from thrift.protocol.TBinaryProtocol import TBinaryProtocol

from hello import Hello
from hello.ttypes import *

host = 'localhost'
port = 9090

def main(arg):
    socket = TSocket.TSocket(host, port)
    transport = TTransport.TBufferedTransport(socket)
    protocol = TBinaryProtocol(transport)

    client = Hello.Client(protocol)

    transport.open()

    req = HelloRequest()
    req.language = Language.DE
    req.greeting = 'moin, moin'

    rsp = client.greet(req)

    print('received response: {}'.format(rsp))

    transport.close()

if __name__ == '__main__':
    try:
        main(sys.argv)
    except Thrift.TException as tx:
        print('%s' % tx.message)
