/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef st060115_CONSTANTS_H
#define st060115_CONSTANTS_H

#include "st060115_types.h"

namespace org { namespace misb {

class st060115Constants {
 public:
  st060115Constants();

};

extern const st060115Constants g_st060115_constants;

}} // namespace

#endif
