/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "st060115_constants.h"

namespace org { namespace misb {

const st060115Constants g_st060115_constants;

st060115Constants::st060115Constants() {
}

}} // namespace

